import { test } from 'node:test';
import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { resolveMetric } from '../lib/platform/metricRegistry.ts';
import { polarity } from '../lib/platform/scales.ts';

const MODULE = fileURLToPath(new URL('../lib/platform/metricRegistry.ts', import.meta.url));

test('polarity() reads the registry before the name regex', () => {
  // the regex alone says +1 (nothing in the name reads as "lower is better")
  assert.equal(polarity('third_down_distance_off'), -1);
  assert.equal(polarity('havoc_def'), 1);
  assert.equal(polarity('adj_def_epa'), -1);
});

test('an unregistered name keeps the regex fallback', () => {
  assert.equal(resolveMetric('turnovers'), null);
  assert.equal(polarity('turnovers'), -1);
});

test('resolveMetric splits side, phase and suffix off a published column', () => {
  const r = resolveMetric('EPAplay_off_pass_rank');
  assert.ok(r);
  assert.equal(r.key, 'EPAplay');
  assert.equal(r.side, 'off');
  assert.equal(r.phase, 'pass');
  assert.equal(r.suffix, '_rank');
  assert.equal(r.polarity, 'higher');
  assert.equal(resolveMetric('not_a_metric'), null);
});

test('metricRegistry.ts is the generator output: the sha256 header matches the body', () => {
  const bytes = readFileSync(MODULE);
  // three header lines; the digest covers every byte after the third newline
  let cut = -1;
  for (let i = 0; i < 3; i++) cut = bytes.indexOf(0x0a, cut + 1);
  assert.ok(cut > 0, 'three header lines');
  const header = bytes.subarray(0, cut).toString('utf8').split('\n');
  assert.equal(header[0], '// generated by sportsdataverse.registry');
  const declared = /^\/\/ sha256: ([0-9a-f]{64})$/.exec(header[2])?.[1];
  assert.ok(declared, 'sha256 header line');
  const actual = createHash('sha256').update(bytes.subarray(cut + 1)).digest('hex');
  assert.equal(actual, declared, 'hand-edited: regenerate with `python -m sportsdataverse.registry --ts --target web`');
});
