// generated by sportsdataverse.registry
// sportsdataverse 0.1.4 -- target web. The sha256 below covers the body (everything after these three header lines), not the whole file; a new sdv-py version rewrites this line, so regenerate on a bump.
// sha256: 3bf634a15188ec726b5d0391ab83eb58424bb95b52a160968f638b011ec489c4
export type Polarity = "higher" | "lower";
export type MetricFormat = "num2" | "num1" | "pct1" | "int";
export type MetricFamily = "efficiency" | "explosiveness" | "volume" | "tendency" | "situational" | "drive" | "adjusted";
export type MetricQualifier = "dropbacks" | "carries" | "targets" | null;
export type MetricSide = "off" | "def" | "margin";
export type MetricPhase = "pass" | "rush";

export interface MetricEntry {
  key: string;
  label: string;
  short: string;
  axis: string;
  format: MetricFormat;
  polarity: Polarity;
  family: MetricFamily;
  qualifier: MetricQualifier;
  glossary_slug: string | null;
  variants: Record<string, string>;
}

/** A resolved column: its base entry, the column's side / phase / suffix and the EFFECTIVE polarity. */
export type ResolvedMetric = MetricEntry & { side?: MetricSide; phase?: MetricPhase; suffix?: string; polarity: Polarity };

export const METRICS: Record<string, MetricEntry> = {
  "TEPA": {
    "key": "TEPA",
    "label": "Total EPA",
    "short": "EPA",
    "axis": "Total EPA",
    "format": "num2",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "TEPA",
      "per_play": "EPAplay",
      "per_game": "EPAgame",
      "per_drive": "EPAdrive"
    }
  },
  "EPAplay": {
    "key": "EPAplay",
    "label": "EPA/Play",
    "short": "EPA/Play",
    "axis": "EPA per play",
    "format": "num2",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "TEPA",
      "per_play": "EPAplay",
      "per_game": "EPAgame",
      "per_drive": "EPAdrive"
    }
  },
  "EPAgame": {
    "key": "EPAgame",
    "label": "EPA/Game",
    "short": "EPA/Game",
    "axis": "EPA per game",
    "format": "num2",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "TEPA",
      "per_play": "EPAplay",
      "per_game": "EPAgame",
      "per_drive": "EPAdrive"
    }
  },
  "EPAdrive": {
    "key": "EPAdrive",
    "label": "EPA/Drive",
    "short": "EPA/Drive",
    "axis": "EPA per drive",
    "format": "num2",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "TEPA",
      "per_play": "EPAplay",
      "per_game": "EPAgame",
      "per_drive": "EPAdrive"
    }
  },
  "EPAdropback": {
    "key": "EPAdropback",
    "label": "EPA/Dropback",
    "short": "EPA/DB",
    "axis": "EPA per dropback",
    "format": "num2",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": "dropbacks",
    "glossary_slug": null,
    "variants": {}
  },
  "EPArush": {
    "key": "EPArush",
    "label": "EPA/Rush",
    "short": "EPA/Rush",
    "axis": "EPA per rush",
    "format": "num2",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": "carries",
    "glossary_slug": null,
    "variants": {}
  },
  "success": {
    "key": "success",
    "label": "Success %",
    "short": "SR%",
    "axis": "Success rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": null,
    "glossary_slug": "success",
    "variants": {}
  },
  "yardsplay": {
    "key": "yardsplay",
    "label": "Yards/Play",
    "short": "Yards/Play",
    "axis": "Yards per play",
    "format": "num2",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "yards",
      "per_play": "yardsplay",
      "per_game": "yardsgame",
      "per_drive": "yardsdrive"
    }
  },
  "yardsgame": {
    "key": "yardsgame",
    "label": "Yards/Game",
    "short": "Yards/Game",
    "axis": "Yards per game",
    "format": "num2",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "yards",
      "per_play": "yardsplay",
      "per_game": "yardsgame",
      "per_drive": "yardsdrive"
    }
  },
  "yardsdrive": {
    "key": "yardsdrive",
    "label": "Yards/Drive",
    "short": "Yards/Drive",
    "axis": "Yards per drive",
    "format": "num2",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "yards",
      "per_play": "yardsplay",
      "per_game": "yardsgame",
      "per_drive": "yardsdrive"
    }
  },
  "yardsdropback": {
    "key": "yardsdropback",
    "label": "Yards/Dropback",
    "short": "Yards/DB",
    "axis": "Yards per dropback",
    "format": "num2",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": "dropbacks",
    "glossary_slug": null,
    "variants": {}
  },
  "havoc": {
    "key": "havoc",
    "label": "Havoc %",
    "short": "Havoc %",
    "axis": "Havoc rate (%)",
    "format": "pct1",
    "polarity": "lower",
    "family": "efficiency",
    "qualifier": null,
    "glossary_slug": "havoc",
    "variants": {}
  },
  "play_stuffed": {
    "key": "play_stuffed",
    "label": "Stuffed %",
    "short": "Stuffed %",
    "axis": "Stuffed rate (%)",
    "format": "pct1",
    "polarity": "lower",
    "family": "efficiency",
    "qualifier": "carries",
    "glossary_slug": null,
    "variants": {}
  },
  "line_yards": {
    "key": "line_yards",
    "label": "Line Yards/Rush",
    "short": "Line Yards",
    "axis": "Line yards per rush",
    "format": "num2",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": "carries",
    "glossary_slug": null,
    "variants": {}
  },
  "opportunity_rate": {
    "key": "opportunity_rate",
    "label": "Rush Opp %",
    "short": "Rush Opp %",
    "axis": "Opportunity rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": "carries",
    "glossary_slug": null,
    "variants": {}
  },
  "catchpct": {
    "key": "catchpct",
    "label": "Catch %",
    "short": "Catch %",
    "axis": "Catch rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "efficiency",
    "qualifier": "targets",
    "glossary_slug": null,
    "variants": {}
  },
  "explosive": {
    "key": "explosive",
    "label": "Explosive %",
    "short": "Explosive %",
    "axis": "Explosive play rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "explosiveness",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "nonExplosiveEpaPerPlay": {
    "key": "nonExplosiveEpaPerPlay",
    "label": "Non-Expl EPA/Play",
    "short": "Non-Expl EPA/Play",
    "axis": "EPA per non-explosive play",
    "format": "num2",
    "polarity": "higher",
    "family": "explosiveness",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "plays": {
    "key": "plays",
    "label": "Total Plays",
    "short": "Plays",
    "axis": "Plays",
    "format": "int",
    "polarity": "higher",
    "family": "volume",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "plays",
      "per_game": "playsgame",
      "per_drive": "playsdrive"
    }
  },
  "playsgame": {
    "key": "playsgame",
    "label": "Plays/Game",
    "short": "Plays/Game",
    "axis": "Plays per game",
    "format": "num2",
    "polarity": "higher",
    "family": "volume",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "plays",
      "per_game": "playsgame",
      "per_drive": "playsdrive"
    }
  },
  "playsdrive": {
    "key": "playsdrive",
    "label": "Plays/Drive",
    "short": "Plays/Drive",
    "axis": "Plays per drive",
    "format": "num2",
    "polarity": "higher",
    "family": "volume",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "plays",
      "per_game": "playsgame",
      "per_drive": "playsdrive"
    }
  },
  "yards": {
    "key": "yards",
    "label": "Total Yards",
    "short": "Yards",
    "axis": "Total yards",
    "format": "num1",
    "polarity": "higher",
    "family": "volume",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "yards",
      "per_play": "yardsplay",
      "per_game": "yardsgame",
      "per_drive": "yardsdrive"
    }
  },
  "sack_adj_yards": {
    "key": "sack_adj_yards",
    "label": "Sack-Adjusted Yards",
    "short": "Sack-Adj Yds",
    "axis": "Sack-adjusted yards",
    "format": "num1",
    "polarity": "higher",
    "family": "volume",
    "qualifier": "dropbacks",
    "glossary_slug": null,
    "variants": {}
  },
  "drives": {
    "key": "drives",
    "label": "Total Drives",
    "short": "Drives",
    "axis": "Drives",
    "format": "int",
    "polarity": "higher",
    "family": "volume",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "drives",
      "per_game": "drivesgame"
    }
  },
  "drivesgame": {
    "key": "drivesgame",
    "label": "Drives/Game",
    "short": "Drives/Game",
    "axis": "Drives per game",
    "format": "num2",
    "polarity": "higher",
    "family": "volume",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {
      "total": "drives",
      "per_game": "drivesgame"
    }
  },
  "dropbacks": {
    "key": "dropbacks",
    "label": "Dropbacks",
    "short": "Dropbacks",
    "axis": "Dropbacks",
    "format": "int",
    "polarity": "higher",
    "family": "volume",
    "qualifier": "dropbacks",
    "glossary_slug": null,
    "variants": {}
  },
  "targets": {
    "key": "targets",
    "label": "Targets",
    "short": "Targets",
    "axis": "Targets",
    "format": "int",
    "polarity": "higher",
    "family": "volume",
    "qualifier": "targets",
    "glossary_slug": null,
    "variants": {}
  },
  "comp": {
    "key": "comp",
    "label": "Catches",
    "short": "Catches",
    "axis": "Catches",
    "format": "int",
    "polarity": "higher",
    "family": "volume",
    "qualifier": "targets",
    "glossary_slug": null,
    "variants": {}
  },
  "games": {
    "key": "games",
    "label": "Games",
    "short": "Games",
    "axis": "Games",
    "format": "int",
    "polarity": "higher",
    "family": "volume",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "passrate": {
    "key": "passrate",
    "label": "Pass %",
    "short": "Pass %",
    "axis": "Pass rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "tendency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "rushrate": {
    "key": "rushrate",
    "label": "Rush %",
    "short": "Rush %",
    "axis": "Rush rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "tendency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "pass_rate": {
    "key": "pass_rate",
    "label": "Pass Rate",
    "short": "Pass Rate",
    "axis": "Pass rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "tendency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "xpass_rate": {
    "key": "xpass_rate",
    "label": "Expected Pass Rate",
    "short": "Expected Pass Rate",
    "axis": "Expected pass rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "tendency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "pass_oe": {
    "key": "pass_oe",
    "label": "Pass Rate Over Expected",
    "short": "PROE",
    "axis": "Pass rate over expected (pts)",
    "format": "num1",
    "polarity": "higher",
    "family": "tendency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "neutral_pass_rate": {
    "key": "neutral_pass_rate",
    "label": "Neutral Pass Rate",
    "short": "Neutral Pass Rate",
    "axis": "Neutral pass rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "tendency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "neutral_xpass_rate": {
    "key": "neutral_xpass_rate",
    "label": "Neutral Expected Pass Rate",
    "short": "Neutral Expected",
    "axis": "Neutral expected pass rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "tendency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "neutral_pass_oe": {
    "key": "neutral_pass_oe",
    "label": "Neutral Pass Rate Over Expected",
    "short": "Neutral PROE",
    "axis": "Neutral pass rate over expected (pts)",
    "format": "num1",
    "polarity": "higher",
    "family": "tendency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "fourth_decisions": {
    "key": "fourth_decisions",
    "label": "Fourth Down Decisions",
    "short": "Decisions",
    "axis": "Fourth-down decisions",
    "format": "int",
    "polarity": "higher",
    "family": "tendency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "fourth_go_rate": {
    "key": "fourth_go_rate",
    "label": "Fourth Down Go Rate",
    "short": "Go Rate",
    "axis": "Fourth-down go rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "tendency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "fourth_go_expected": {
    "key": "fourth_go_expected",
    "label": "Model Fourth Down Go Rate",
    "short": "Model Go Rate",
    "axis": "Model go rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "tendency",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "fourth_go_over_expected": {
    "key": "fourth_go_over_expected",
    "label": "Fourth Down Go Rate Over Expected",
    "short": "Go Rate Over Expected",
    "axis": "Go rate over expected (pts)",
    "format": "pct1",
    "polarity": "higher",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "fourth_go_boost": {
    "key": "fourth_go_boost",
    "label": "Average Fourth Down Boost",
    "short": "Avg Boost",
    "axis": "Average win-probability boost (pts)",
    "format": "num2",
    "polarity": "higher",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "fourth_go_when_recommended": {
    "key": "fourth_go_when_recommended",
    "label": "Went For It When Recommended",
    "short": "Went When Told To",
    "axis": "Went when recommended (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "series_conv": {
    "key": "series_conv",
    "label": "Series Conversion Rate",
    "short": "Series Conv %",
    "axis": "Series conversion rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "luck_fumble_rec_pct": {
    "key": "luck_fumble_rec_pct",
    "label": "Fumble Recovery Rate",
    "short": "Fumbles Recovered",
    "axis": "Fumble recovery rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "luck_opp_fg_pct": {
    "key": "luck_opp_fg_pct",
    "label": "Opponent Field Goal Percentage",
    "short": "Opp FG%",
    "axis": "Opponent field-goal percentage (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "red_zone_success": {
    "key": "red_zone_success",
    "label": "Red Zone SR%",
    "short": "RZ SR%",
    "axis": "Red-zone success rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "third_down_success": {
    "key": "third_down_success",
    "label": "3rd Down SR%",
    "short": "3rd Down SR%",
    "axis": "Third-down success rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "third_down_distance": {
    "key": "third_down_distance",
    "label": "Avg Distance (3rd)",
    "short": "3rd Down Dist",
    "axis": "Average third-down distance (yards)",
    "format": "num2",
    "polarity": "lower",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "late_down_success": {
    "key": "late_down_success",
    "label": "Late Down SR%",
    "short": "Late Down SR%",
    "axis": "Late-down success rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "early_down_EPA": {
    "key": "early_down_EPA",
    "label": "Early Down EPA/Play",
    "short": "Early Down EPA/Play",
    "axis": "Early-down EPA per play",
    "format": "num2",
    "polarity": "higher",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "early_down_success": {
    "key": "early_down_success",
    "label": "Early Down SR%",
    "short": "Early Down SR%",
    "axis": "Early-down success rate (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "situational",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "start_position": {
    "key": "start_position",
    "label": "Starting Field Position",
    "short": "Start Pos",
    "axis": "Starting field position (yards to goal)",
    "format": "num2",
    "polarity": "lower",
    "family": "drive",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "total_available_yards": {
    "key": "total_available_yards",
    "label": "Total Available Yards",
    "short": "Avail Yards",
    "axis": "Available yards",
    "format": "int",
    "polarity": "higher",
    "family": "drive",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "total_gained_yards": {
    "key": "total_gained_yards",
    "label": "Total Gained Yards",
    "short": "Gained Yards",
    "axis": "Gained yards",
    "format": "int",
    "polarity": "higher",
    "family": "drive",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "available_yards_pct": {
    "key": "available_yards_pct",
    "label": "Available Yards %",
    "short": "Avail Yards %",
    "axis": "Available yards gained (%)",
    "format": "pct1",
    "polarity": "higher",
    "family": "drive",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "pts_per_drive": {
    "key": "pts_per_drive",
    "label": "Points/Drive",
    "short": "Pts/Drive",
    "axis": "Points per drive",
    "format": "num2",
    "polarity": "higher",
    "family": "drive",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "pts_per_opp": {
    "key": "pts_per_opp",
    "label": "Points/Scoring Opportunity",
    "short": "Pts/Opp",
    "axis": "Points per scoring opportunity",
    "format": "num2",
    "polarity": "higher",
    "family": "drive",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "drive_start_ep": {
    "key": "drive_start_ep",
    "label": "Starting Expected Points",
    "short": "Start EP",
    "axis": "Expected points at drive start",
    "format": "num2",
    "polarity": "higher",
    "family": "drive",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "adj_epa": {
    "key": "adj_epa",
    "label": "Adj EPA/Play",
    "short": "Adj EPA/Play",
    "axis": "Opponent-adjusted EPA per play",
    "format": "num2",
    "polarity": "higher",
    "family": "adjusted",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  },
  "strength_faced": {
    "key": "strength_faced",
    "label": "Strength Faced",
    "short": "Strength Faced",
    "axis": "Opponent strength faced (EPA per play)",
    "format": "num2",
    "polarity": "higher",
    "family": "adjusted",
    "qualifier": null,
    "glossary_slug": null,
    "variants": {}
  }
};

const SUFFIXES = ["_pos_pct", "_conf_pct", "_rank", "_pct", "_n"];
const PHASES: MetricPhase[] = ["pass", "rush"];
const SIDES: MetricSide[] = ["off", "def", "margin"];
type PhaseWords = Record<MetricPhase, [string, Record<string, string>]>;
const LABEL_WORDS: PhaseWords = { pass: ["Pass", { Play: "Dropback", Plays: "Dropbacks" }], rush: ["Rush", { Play: "Rush", Plays: "Rushes" }] };
const SHORT_WORDS: PhaseWords = { pass: ["Pass", { Play: "DB", Plays: "Dropbacks" }], rush: LABEL_WORDS.rush };
const has = (key: string): boolean => Object.prototype.hasOwnProperty.call(METRICS, key);
// only the adjusted columns spell their side as a prefix / infix (adj_off_epa, off_strength_faced, net_adj_epa)
const adjusted = (key: string): boolean => has(key) && METRICS[key].family === "adjusted";

function phased(text: string, phase: MetricPhase | undefined, words: PhaseWords): string {
  if (!phase) return text;
  const [prefix, swap] = words[phase];
  if (/\bPlays?\b/.test(text)) return text.replace(/\bPlays?\b/g, (m) => swap[m]);
  return text.startsWith(prefix) ? text : `${prefix} ${text}`;
}

function split(column: string): [string, MetricSide | undefined, MetricPhase | undefined, string | undefined] | null {
  // the exact column first, so a registered X_pct is never read as X + _pct
  for (const suffix of [undefined, ...SUFFIXES]) {
    if (suffix !== undefined && !column.endsWith(suffix)) continue;
    let stem = suffix ? column.slice(0, -suffix.length) : column;
    const phase = PHASES.find((p) => stem.endsWith(`_${p}`));
    if (phase) stem = stem.slice(0, -phase.length - 1);
    const side = SIDES.find((s) => stem.endsWith(`_${s}`));
    if (side) stem = stem.slice(0, -side.length - 1);
    if (has(stem)) return [stem, side, phase, suffix];
    if (!side && !phase) {
      const net = /^net_(.+)$/.exec(stem);
      if (net && adjusted(net[1])) return [net[1], "margin", undefined, suffix];
      const infix = /^(?:(.+)_)?(off|def)_(.+)$/.exec(stem);
      if (infix) {
        const base = infix[1] ? `${infix[1]}_${infix[3]}` : infix[3];
        if (adjusted(base)) return [base, infix[2] as MetricSide, undefined, suffix];
      }
    }
  }
  return null;
}

/** The entry behind a published column, or null. `_def` flips the polarity; a `_margin` is always higher-is-better. */
export function resolveMetric(column: string): ResolvedMetric | null {
  const found = split(column);
  if (!found) return null;
  const [key, side, phase, suffix] = found;
  const entry = METRICS[key];
  let polarity: Polarity = entry.polarity;
  if (side === "def") polarity = polarity === "higher" ? "lower" : "higher";
  else if (side === "margin") polarity = "higher";
  const out: ResolvedMetric = {
    ...entry,
    variants: { ...entry.variants },
    label: phased(entry.label, phase, LABEL_WORDS),
    short: phased(entry.short, phase, SHORT_WORDS),
    polarity,
  };
  if (side) out.side = side;
  if (phase) out.phase = phase;
  if (suffix) out.suffix = suffix;
  return out;
}
