on:
  workflow_dispatch:
  #push:
  #  branches:
  #    - main
  schedule:
    - cron: '0 4 * * *'

name: Update data

jobs:
  build:
    name: Update data
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5
        with:
          ref: with-data
      - uses: actions/setup-python@v6
        with:
            python-version: '3.12'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Update data
        run: cd python && TOKEN=${{ secrets.GITHUB_TOKEN }} python data_fetcher.py
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> "$GITHUB_OUTPUT"
      - uses: stefanzweifel/git-auto-commit-action@778341af668090896ca464160c2def5d1d1a3eb0 # v6
        with:
          commit_message: Update ${{ steps.date.outputs.date }}
          branch: with-data
          commit_author: Auto fetch <actions@github.com> # defaults to author of the commit that triggered the run
          add_options: '-u'
